settings:
  title: 'Status Page'
  url: 'https://status.digisense.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: quickpage-digisense-io
    name: quickpage.digisense.io
    url: 'https://quickpage.digisense.io/'
    method: GET
    expectStatus: 200
  - id: store-api-endpoint
    name: Store API endpoint
    url: 'https://store-api.digisense.io/health'
    method: GET
    expectStatus: 200
    linkable: false
  - id: org-api-endpoint
    name: Organization API endpoint
    url: 'https://org-api.digisense.io/health'
    method: GET
    expectStatus: 200
    linkable: false
  - id: quickpage-api-endpoint
    name: Quickapge API endpoint
    url: 'https://quickpage-api.digisense.io/health'
    method: GET
    expectStatus: 200
    linkable: false
  - id: authen-api-endpoint
    name: Authen API endpoint
    url: 'https://authen.digisense.io/health'
    method: GET
    expectStatus: 200
    linkable: false
  - id: hydra-endpoint
    name: Hydra API endpoint
    url: 'https://hydra.digisense.io/health/ready'
    method: GET
    expectStatus: 200
    linkable: false
  - id: kratos-endpoint
    name: Kratos API endpoint
    url: 'https://kratos.digisense.io/health/ready'
    method: GET
    expectStatus: 200
    linkable: false
